In [3]:
import numpy as np

students = np.array(["Alice", "Bob", "Charlie", "David"])
subjects = np.array(["Math", "Science", "English"])

marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 88, 95],
    [70, 75, 72]
])

print("Marks Array:\n", marks)


Marks Array:
 [[85 90 88]
 [78 82 80]
 [92 88 95]
 [70 75 72]]


In [4]:
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Size:", marks.size)
print("Data Type:", marks.dtype)


Shape: (4, 3)
Dimensions: 2
Size: 12
Data Type: int64


In [5]:
reshaped_marks = marks.reshape(3, 4)  # reshape (4x3) → (3x4)
print("Reshaped Marks:\n", reshaped_marks)


Reshaped Marks:
 [[85 90 88 78]
 [82 80 92 88]
 [95 70 75 72]]


In [6]:
# Adding a new student
new_student = np.array([[88, 91, 85]])
updated_marks = np.vstack((marks, new_student))
print("After Adding New Student:\n", updated_marks)

# Adding a new subject
new_subject = np.array([[80], [85], [90], [75], [88]])
updated_marks_with_subject = np.hstack((updated_marks, new_subject))
print("After Adding New Subject:\n", updated_marks_with_subject)


After Adding New Student:
 [[85 90 88]
 [78 82 80]
 [92 88 95]
 [70 75 72]
 [88 91 85]]
After Adding New Subject:
 [[85 90 88 80]
 [78 82 80 85]
 [92 88 95 90]
 [70 75 72 75]
 [88 91 85 88]]


In [7]:
# Update marks
marks[1, 2] = 85  # Update Bob's English mark
print("Updated Marks:\n", marks)

# Identify unique marks
unique_marks = np.unique(marks)
print("Unique Marks:", unique_marks)


Updated Marks:
 [[85 90 88]
 [78 82 85]
 [92 88 95]
 [70 75 72]]
Unique Marks: [70 72 75 78 82 85 88 90 92 95]


In [8]:
marks_float = marks.astype(float)
print("Marks as Float Type:\n", marks_float)


Marks as Float Type:
 [[85. 90. 88.]
 [78. 82. 85.]
 [92. 88. 95.]
 [70. 75. 72.]]


In [9]:
# Create a copy
marks_copy = marks.copy()
marks_copy[0, 0] = 100
print("Original Marks:\n", marks)
print("Copied Marks:\n", marks_copy)

# Create a view
marks_view = marks.view()
marks_view[0, 1] = 99
print("After Modifying View:\n", marks)


Original Marks:
 [[85 90 88]
 [78 82 85]
 [92 88 95]
 [70 75 72]]
Copied Marks:
 [[100  90  88]
 [ 78  82  85]
 [ 92  88  95]
 [ 70  75  72]]
After Modifying View:
 [[85 99 88]
 [78 82 85]
 [92 88 95]
 [70 75 72]]
