In [3]:
import numpy as np


students = np.array(["Alice", "Bob", "Charlie", "David", "Emma"])
subjects = np.array(["Math", "Science", "English", "History"])


marks = np.array([
    [85, 78, 92, 88],
    [76, 85, 80, 70],
    [90, 88, 91, 85],
    [69, 72, 75, 68],
    [95, 89, 96, 90]
])

print(" 1 Data Creation ===")
print("Students:", students)
print("Subjects:", subjects)
print("Marks:\n", marks)

#
# 2️
print("\n 2 Data Exploration ===")
print("Shape of marks:", marks.shape)      # (5,4)
print("Dimensions:", marks.ndim)           # 2
print("Total elements:", marks.size)       # 20
print("Data type:", marks.dtype)
print("Student count:", len(students))
print("Subject count:", len(subjects))

# 3

print("\n 3 Data Transformation ===")

flat_marks = marks.flatten()              # Flatten marks
print("Flattened Marks:", flat_marks)


reshaped = flat_marks.reshape(4, 5)         # Reshape
print("Reshaped Marks (4x5):\n", reshaped)


transposed = marks.T                          # Transpose: subjects become rows, students become columns
print("Transposed Marks:\n", transposed)

#$
print("\n 4 Data Combination ===")


new_student = np.array(["Frank"])           # Add a new student
new_marks = np.array([[82, 80, 84, 79]])

students = np.concatenate((students, new_student))
marks = np.vstack((marks, new_marks))

print("Updated Students:", students)
print("Updated Marks:\n", marks)


new_subject = np.array(["Geography"])       # Add a new subject
new_subject_marks = np.array([[88], [75], [85], [72], [90], [78]])

subjects = np.concatenate((subjects, new_subject))
marks = np.hstack((marks, new_subject_marks))

print("\nAfter Adding Subject:")
print("Subjects:", subjects)
print("Marks:\n", marks)


#5
print("\n 5 Data Modification ===")

marks[1, 1] = 90
print("Updated Bob’s Science Mark:", marks[1])


index_david = np.where(students == "David")[0][0]   # Remove a student
marks = np.delete(marks, index_david, axis=0)
students = np.delete(students, index_david)
print("Removed David. Updated Students:", students)
print("Updated Marks:\n", marks)


unique_subjects = np.unique(subjects)             # Unique subject names
print("Unique Subjects:", unique_subjects)


print("\n 6 Data Type Handling ===")

marks_float = marks.astype(float)
print("Marks as Float:\n", marks_float)

marks_str = marks.astype(str)
print("Marks as String:\n", marks_str)

avg_marks = np.mean(marks_float, axis=1)
print("Average marks (float array):", avg_marks)


print("\n 7 Copy and View Behavior ===")

marks_view = marks.view()
marks_copy = marks.copy()               # Create a view

marks_view[0, 0] = 100  # Changing first student's first subject mark

print("Original Marks after modifying view:\n", marks)
print("Marks Copy (unchanged):\n", marks_copy)

print("\n✔️ Difference: View shares memory; Copy is independent.")


 1 Data Creation ===
Students: ['Alice' 'Bob' 'Charlie' 'David' 'Emma']
Subjects: ['Math' 'Science' 'English' 'History']
Marks:
 [[85 78 92 88]
 [76 85 80 70]
 [90 88 91 85]
 [69 72 75 68]
 [95 89 96 90]]

 2 Data Exploration ===
Shape of marks: (5, 4)
Dimensions: 2
Total elements: 20
Data type: int64
Student count: 5
Subject count: 4

 3 Data Transformation ===
Flattened Marks: [85 78 92 88 76 85 80 70 90 88 91 85 69 72 75 68 95 89 96 90]
Reshaped Marks (4x5):
 [[85 78 92 88 76]
 [85 80 70 90 88]
 [91 85 69 72 75]
 [68 95 89 96 90]]
Transposed Marks:
 [[85 76 90 69 95]
 [78 85 88 72 89]
 [92 80 91 75 96]
 [88 70 85 68 90]]

 4 Data Combination ===
Updated Students: ['Alice' 'Bob' 'Charlie' 'David' 'Emma' 'Frank']
Updated Marks:
 [[85 78 92 88]
 [76 85 80 70]
 [90 88 91 85]
 [69 72 75 68]
 [95 89 96 90]
 [82 80 84 79]]

After Adding Subject:
Subjects: ['Math' 'Science' 'English' 'History' 'Geography']
Marks:
 [[85 78 92 88 88]
 [76 85 80 70 75]
 [90 88 91 85 85]
 [69 72 75 68 72]
 [95 